apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j86irlj20-nodejs
  janus-idp.io/tekton: j86irlj20-nodejs
  backstage.io/kubernetes-id: j86irlj20-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j86irlj20-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
